/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASK_H_RPCGEN
#define _ASK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputsMo {
	int resultMo;
	struct {
		u_int b_len;
		int *b_val;
	} b;
};
typedef struct inputsMo inputsMo;

struct inputsMinMax {
	struct {
		u_int minMax_len;
		int *minMax_val;
	} minMax;
	struct {
		u_int b_len;
		int *b_val;
	} b;
};
typedef struct inputsMinMax inputsMinMax;

struct inputsMul {
	int mult;
	struct {
		u_int mulArr_len;
		int *mulArr_val;
	} mulArr;
	struct {
		u_int b_len;
		int *b_val;
	} b;
};
typedef struct inputsMul inputsMul;

#define ask_PROG 0x23451111
#define ask_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define mo 1
extern  inputsMo * mo_1(inputsMo *, CLIENT *);
extern  inputsMo * mo_1_svc(inputsMo *, struct svc_req *);
#define minmax 2
extern  inputsMinMax * minmax_1(inputsMinMax *, CLIENT *);
extern  inputsMinMax * minmax_1_svc(inputsMinMax *, struct svc_req *);
#define mul 3
extern  inputsMul * mul_1(inputsMul *, CLIENT *);
extern  inputsMul * mul_1_svc(inputsMul *, struct svc_req *);
extern int ask_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mo 1
extern  inputsMo * mo_1();
extern  inputsMo * mo_1_svc();
#define minmax 2
extern  inputsMinMax * minmax_1();
extern  inputsMinMax * minmax_1_svc();
#define mul 3
extern  inputsMul * mul_1();
extern  inputsMul * mul_1_svc();
extern int ask_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputsMo (XDR *, inputsMo*);
extern  bool_t xdr_inputsMinMax (XDR *, inputsMinMax*);
extern  bool_t xdr_inputsMul (XDR *, inputsMul*);

#else /* K&R C */
extern bool_t xdr_inputsMo ();
extern bool_t xdr_inputsMinMax ();
extern bool_t xdr_inputsMul ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASK_H_RPCGEN */
