/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask.h"

inputsMo* mo_1_svc(inputsMo *argp, struct svc_req *rqstp)
{
	static inputsMo  result;
	int sum = 0;	

	printf ("===============================================================\n");

	printf ("check variables passed to process mo\n");
	printf ("arrL is = %d\n", argp->b.b_len);
	for (int i=0; i<argp->b.b_len; i++)
	{
		printf ("number %d is = %d\n", i, argp->b.b_val[i]);
	}	
	printf ("===============================================================\n");
	
	for (int i=0; i<argp->b.b_len; i++)
	{
		sum += argp->b.b_val[i]; 
	}
	
	int temp = sum / (argp->b.b_len);
	result.resultMo = temp;
	printf ("result found in server is = %d\n", temp);
	printf ("returning = %d\n", result.resultMo);
	return &result;

}

inputsMinMax* minmax_1_svc(inputsMinMax *argp, struct svc_req *rqstp)
{
	static inputsMinMax  result;
	int min = argp->b.b_val[0], max = argp->b.b_val[0]  ;

	printf ("===============================================================\n");

	printf ("check variables passed to process mo\n");
	printf ("arrL is = %d\n", argp->b.b_len);
	for (int i=0; i<argp->b.b_len; i++)
	{
		printf ("number %d is = %d\n", i, argp->b.b_val[i]);
	}	
	printf ("===============================================================\n");
	
	for (int i=0; i<argp->b.b_len; i++)
	{
		if (min > argp->b.b_val[i])
		{
			min = argp->b.b_val[i];
		} 
		if (max < argp->b.b_val[i])
		{
			max = argp->b.b_val[i];
		} 
	}
	
	result.minMax.minMax_len= 2;
	result.minMax.minMax_val= (int *) malloc(2*sizeof(int)); 
	result.minMax.minMax_val[0] = min;
	result.minMax.minMax_val[1] = max;
	printf ("servers min = %d\n and max = %d\n", min, max);
	printf ("returning min = %d\n and max = %d\n", result.minMax.minMax_val[0], 		       result.minMax.minMax_val[1]);
	
	return &result;

}

inputsMul* mul_1_svc(inputsMul *argp, struct svc_req *rqstp)
{
	static inputsMul  result;
	
	printf ("===============================================================\n");

	printf ("check variables passed to process mo\n");
	printf ("arrL is = %d\n", argp->b.b_len);
	printf ("multiplier is = %d\n", argp->mult);
	for (int i=0; i<argp->b.b_len; i++)
	{
		printf ("number %d is = %d\n", i, argp->b.b_val[i]);
	}	
	printf ("===============================================================\n");
	
	result.mulArr.mulArr_len= argp->b.b_len;
	result.mulArr.mulArr_val = (int *) malloc((argp->b.b_len)*sizeof(int));
	for (int i=0; i<argp->b.b_len; i++)
	{
		result.mulArr.mulArr_val[i] = (argp->b.b_val[i]) * (argp->mult);
		printf ("server returnes mult/ed num #%d = %d\n",i+1 ,result.mulArr.mulArr_val[i]);
	}
	return &result;
}
