/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ask.h"

bool_t
xdr_inputsMo (XDR *xdrs, inputsMo *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->resultMo))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->b.b_val, (u_int *) &objp->b.b_len, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_inputsMinMax (XDR *xdrs, inputsMinMax *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->minMax.minMax_val, (u_int *) &objp->minMax.minMax_len, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->b.b_val, (u_int *) &objp->b.b_len, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_inputsMul (XDR *xdrs, inputsMul *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->mult))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->mulArr.mulArr_val, (u_int *) &objp->mulArr.mulArr_len, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->b.b_val, (u_int *) &objp->b.b_len, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
