/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ask.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

inputsMo *
mo_1(inputsMo *argp, CLIENT *clnt)
{
	static inputsMo clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, mo,
		(xdrproc_t) xdr_inputsMo, (caddr_t) argp,
		(xdrproc_t) xdr_inputsMo, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

inputsMinMax *
minmax_1(inputsMinMax *argp, CLIENT *clnt)
{
	static inputsMinMax clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, minmax,
		(xdrproc_t) xdr_inputsMinMax, (caddr_t) argp,
		(xdrproc_t) xdr_inputsMinMax, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

inputsMul *
mul_1(inputsMul *argp, CLIENT *clnt)
{
	static inputsMul clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, mul,
		(xdrproc_t) xdr_inputsMul, (caddr_t) argp,
		(xdrproc_t) xdr_inputsMul, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
